<?php

namespace Database\Seeders;

use App\Models\Program;
use App\Models\ProgramGrowthStage;
use Illuminate\Database\Seeder;

class SteamProgramSeeder extends Seeder
{
    public function run(): void
    {
        $programs = [
            [
                'name' => 'Science',
                'slug' => 'science',
                'discipline' => 'science',
                'tagline' => 'Dissect Reality. Command Microbes. Chart the Stars.',
                'ages' => '3–18',
                'color' => '#00FF88',
                'accent_color' => '#052E16',
                'gradient' => 'linear-gradient(135deg,#052E16 0%,#064e3b 50%,#00FF88 100%)',
                'icon_svg' => '<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19.428 15.428a2 2 0 00-1.022-.547l-2.387-.477a6 6 0 00-3.86.517l-.318.158a6 6 0 01-3.86.517L6.05 15.21a2 2 0 00-1.806.547M8 4h8l-1 1v5.172a2 2 0 00.586 1.414l5 5c1.26 1.26.367 3.414-1.415 3.414H4.828c-1.782 0-2.674-2.154-1.414-3.414l5-5A2 2 0 009 10.172V5L8 4z"/>',
                'description' => 'Science at TLab isn’t dusty textbooks—it is a rogue bio-physical exploration unit. From inspecting pond water monsters under digital microscopes to synthesizing plant hydrogels and modeling orbital mechanics, children learn to challenge every assumption and demand physical proof.',
                'what_learn' => [
                    'Microbiology & cellular anatomy',
                    'Chemical reactions & crystal synthesis',
                    'Environmental thermodynamics & climate telemetry',
                    'Astro-physics & satellite tracking',
                    'Genetics & CRISPR bioethics simulations',
                    'Experimental lab logging & empirical data rigour',
                ],
                'outcomes' => [
                    'Formulate testable hypotheses without adult prompting',
                    'Operate digital microscopes and sensor spectrophotometers',
                    'Design and conduct controlled double-blind experiments',
                    'Publish peer-reviewed student science lab briefs',
                    'Compete in regional & pan-African science Olympiads',
                ],
                'career_paths' => [
                    'Biomedical Engineer',
                    'Astrobiologist',
                    'Climate Data Scientist',
                    'Genetic Researcher',
                    'Nanotechnologist',
                ],
                'sort_order' => 1,
                'stages' => [
                    [
                        'stage_name' => 'Spore Observers',
                        'age_band' => 'Ages 3–5',
                        'min_age' => 3,
                        'max_age' => 5,
                        'focus_title' => 'Sensory Wonder & Micro-Discoveries',
                        'description' => 'Toddlers touch, smell, dissolve, freeze, and observe. Introducing natural phenomena through tactile experiments that build intuitive physics and biology.',
                        'skills' => ['Sensory categorization', 'Magnifier observation', 'Liquid density play', 'Seed growth charting'],
                        'milestones' => ['Built first terrarium capsule', 'Identified 10 plant structures', 'Logged first leaf discoloration experiment'],
                        'tools_used' => ['Handheld optical loupes', 'Non-toxic pipettes', 'Agar petri plates', 'Color mixing test-tubes'],
                        'featured_project' => 'Living Bio-Dome Terrarium with Self-Sustaining Moss',
                    ],
                    [
                        'stage_name' => 'Junior Alchemists',
                        'age_band' => 'Ages 6–8',
                        'min_age' => 6,
                        'max_age' => 8,
                        'focus_title' => 'States of Matter & Kitchen Chemistry',
                        'description' => 'Young investigators trigger safe exothermic reactions, build crystal gardens, and explore animal adaptations with field notebooks.',
                        'skills' => ['pH scale testing', 'State-change timing', 'Solar energy capture', 'Classification of living organisms'],
                        'milestones' => ['Extracted plant chlorophyll', 'Constructed a working baking soda volcanic geyser', 'Created an optical prism rainbow index'],
                        'tools_used' => ['Litmus indicators', 'Digital thermometers', 'Prisms & UV torches', 'Magnifying microscopes'],
                        'featured_project' => 'Glowing Luminescent Slime & Geode Crystal Garden',
                    ],
                    [
                        'stage_name' => 'Ecosystem Hackers',
                        'age_band' => 'Ages 9–11',
                        'min_age' => 9,
                        'max_age' => 11,
                        'focus_title' => 'Cellular Biomes & Environmental Sensors',
                        'description' => 'Students sample real-world water sources, track ambient air quality using IoT sensors, and examine protozoa under 400x magnification.',
                        'skills' => ['Microscopic slide mounting', 'Sensor data logging', 'Photosynthetic rate measurement', 'Soil nutrient titrations'],
                        'milestones' => ['Mapped municipal tap water vs rain puddle organisms', 'Designed a greywater filtration matrix', 'Calculated local carbon absorption'],
                        'tools_used' => ['Compound optical microscope', 'Soil NPK probe', 'Digital hydrometer', 'Microbiology stain kits'],
                        'featured_project' => 'Multi-Tier Water Bio-Filtration Column with Live Bio-Indicators',
                    ],
                    [
                        'stage_name' => 'Biotech Navigators',
                        'age_band' => 'Ages 12–14',
                        'min_age' => 12,
                        'max_age' => 14,
                        'focus_title' => 'Genetics, Optics & Thermodynamics',
                        'description' => 'Isolate real strawberry DNA, model viral transmission with mathematical agents, and calculate heat dissipation in miniature green buildings.',
                        'skills' => ['Ethanol DNA precipitation', 'Spectroscopy analysis', 'Newtonian gravity orbital simulations', 'Epidemiological modeling'],
                        'milestones' => ['Extracted intact genomic DNA threads', 'Constructed a passive solar cooling chamber', 'Simulated viral transmission curves'],
                        'tools_used' => ['Centrifuge mini-vortex', 'UV transilluminator', 'Spectroscope chamber', 'Tracker physics video software'],
                        'featured_project' => 'Strawberry DNA Extraction Matrix & CRISPR Gene-Drive Interactive Model',
                    ],
                    [
                        'stage_name' => 'Synthetic Biology Pioneers',
                        'age_band' => 'Ages 15–18',
                        'min_age' => 15,
                        'max_age' => 18,
                        'focus_title' => 'Applied Bio-Hacking & Astrobiology Research',
                        'description' => 'Pre-university scholars formulate genuine research papers. From hydroponic automation to microbial fuel cells that generate measurable electricity.',
                        'skills' => ['Bioinformatics BLAST searches', 'Electrochemical battery construction', 'Statistical p-value validation', 'Scientific paper writing'],
                        'milestones' => ['Generated 1.2V from mud microbial fuel cells', 'Drafted a formal preprint research brief', 'Presented at regional STEM summit'],
                        'tools_used' => ['Gel electrophoresis kit', 'Potentiometer', 'Hydroponic nutrient doser', 'Python SciPy & Biopython'],
                        'featured_project' => 'MudWatt Microbial Fuel Cell & Automated Micro-Algae Photobioreactor',
                    ],
                ],
            ],
            [
                'name' => 'Technology',
                'slug' => 'technology',
                'discipline' => 'technology',
                'tagline' => 'Bend Silicon to Your Will. Build Autonomous Minds.',
                'ages' => '3–18',
                'color' => '#00E5FF',
                'accent_color' => '#021B2B',
                'gradient' => 'linear-gradient(135deg,#021B2B 0%,#083344 50%,#00E5FF 100%)',
                'icon_svg' => '<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4"/>',
                'description' => 'From drag-and-drop spatial algorithms for 4-year-olds to building custom neural networks and automated cyber defenses by age 16. Technology at TLab is never passive screen consumption—it is pure creator sorcery.',
                'what_learn' => [
                    'Algorithmic decomposition & computational logic',
                    'Block-based logic (Scratch, Blockly, MakeCode)',
                    'Modern Python for automation & algorithmic data',
                    'Full-stack Web architecture (HTML, CSS, JS, API design)',
                    'Applied Artificial Intelligence & neural prompt engineering',
                    'Cyber hygiene, penetration testing fundamentals & cryptography',
                ],
                'outcomes' => [
                    'Ship live web applications hosted on public URLs',
                    'Train and deploy a lightweight machine learning classifier',
                    'Architect multi-level playable 2D games with physics engines',
                    'Automate repetitive tasks with custom Python bots',
                    'Participate in student hackathons and open-source bounties',
                ],
                'career_paths' => [
                    'AI Systems Engineer',
                    'Full-Stack Web Architect',
                    'Cybersecurity Defense Analyst',
                    'Cloud Infrastructure Dev',
                    'Product Algorithm Lead',
                ],
                'sort_order' => 2,
                'stages' => [
                    [
                        'stage_name' => 'Pixel Tamers',
                        'age_band' => 'Ages 3–5',
                        'min_age' => 3,
                        'max_age' => 5,
                        'focus_title' => 'Spatial Sequence & Tangible Algorithms',
                        'description' => 'Screen-free tactile coding mats, directional logic games, and introducing the concept that computers execute step-by-step instructions without mind-reading.',
                        'skills' => ['Directional sequencing (Forward, Left, Right)', 'Bug finding in human games', 'Pattern recognition', 'Cause-and-effect loops'],
                        'milestones' => ['Guided physical floor-bot through 10-step maze', 'Arranged sequence cards to tell automated story', 'Identified endless loop glitch'],
                        'tools_used' => ['Bee-Bot floor robot', 'Primo Cubetto wooden blocks', 'ScratchJr on rugged tablets', 'Tactile algorithm tiles'],
                        'featured_project' => 'Interactive Floor Maze Bot Rescue Mission with Physical Command Cards',
                    ],
                    [
                        'stage_name' => 'Scratch Sorcerers',
                        'age_band' => 'Ages 6–8',
                        'min_age' => 6,
                        'max_age' => 8,
                        'focus_title' => 'Event Loops, Variables & Game Mechanics',
                        'description' => 'Children move from consumers to game designers. Learning coordinate planes (X, Y), sprite animation, score tracking, and conditional branching.',
                        'skills' => ['If/Else conditionals', 'Broadcast messaging', 'Variable counters (Lives, Score)', 'Collision detection'],
                        'milestones' => ['Published playable platformer game', 'Built multi-character animated comic strip', 'Debugged another peer’s game logic'],
                        'tools_used' => ['Scratch 3.0', 'MakeCode Arcade', 'Canva for pixel sprites', 'Tynker block engine'],
                        'featured_project' => 'Super Space Glitch: Custom 3-Level Retro Arcade Platformer',
                    ],
                    [
                        'stage_name' => 'Python Constructors',
                        'age_band' => 'Ages 9–11',
                        'min_age' => 9,
                        'max_age' => 11,
                        'focus_title' => 'Text-Based Syntax & Procedural Logic',
                        'description' => 'The great leap into real syntax. Python loops, lists, dictionaries, functions, and building terminal-based adventure simulations and math solvers.',
                        'skills' => ['Python data structures', 'Function parameters & return values', 'Turtle graphics geometry', 'Handling user runtime input errors'],
                        'milestones' => ['Wrote 200-line text adventure engine', 'Generated recursive fractal trees with Turtle', 'Automated math homework verification bot'],
                        'tools_used' => ['Python 3 IDLE', 'VS Code / Replit', 'Pygame Zero', 'ASCII Art generators'],
                        'featured_project' => 'Cyber Dungeon RPG: Terminal-Based Battle Engine with Inventory System',
                    ],
                    [
                        'stage_name' => 'Neural & Web Architects',
                        'age_band' => 'Ages 12–14',
                        'min_age' => 12,
                        'max_age' => 14,
                        'focus_title' => 'Full-Stack Web & Applied AI APIs',
                        'description' => 'Connecting frontends to backends. Building modern web interfaces, consuming REST APIs, and training computer vision models via Teachable Machine.',
                        'skills' => ['HTML5 semantic layout & CSS Grid', 'JavaScript DOM manipulation', 'REST API fetching (fetch / axios)', 'Machine learning image classification'],
                        'milestones' => ['Deployed live website to Vercel/Netlify', 'Integrated live weather API data feed', 'Trained gesture-recognition web controller'],
                        'tools_used' => ['Modern JavaScript (ES6)', 'Tailwind CSS', 'FastAPI / Flask', 'Teachable Machine / Hugging Face'],
                        'featured_project' => 'AI Waste-Classifier Web App Powered by Custom Vision Model & REST API',
                    ],
                    [
                        'stage_name' => 'Autonomous Systems Engineers',
                        'age_band' => 'Ages 15–18',
                        'min_age' => 15,
                        'max_age' => 18,
                        'focus_title' => 'Production Architectures & Neural Networks',
                        'description' => 'Writing production-ready code. Relational databases, authentication tokens, containerization, and fine-tuning lightweight neural language models.',
                        'skills' => ['SQL relational modeling', 'Git collaborative branching', 'Docker container basics', 'PyTorch / TensorFlow neural networks'],
                        'milestones' => ['Shipped SaaS micro-tool with database storage', 'Contributed PR to open-source repo', 'Trained custom LLM fine-tune for local dialect'],
                        'tools_used' => ['Python PyTorch', 'PostgreSQL / Supabase', 'Docker', 'GitHub Actions CI/CD'],
                        'featured_project' => 'AfriVoice AI: Local Dialect Speech-to-Text Micro-SaaS with PostgreSQL Backend',
                    ],
                ],
            ],
            [
                'name' => 'Engineering',
                'slug' => 'engineering',
                'discipline' => 'engineering',
                'tagline' => 'Wrench. Solder. Breathe Life into Metal & Circuits.',
                'ages' => '3–18',
                'color' => '#FFB800',
                'accent_color' => '#2A1702',
                'gradient' => 'linear-gradient(135deg,#2A1702 0%,#78350F 50%,#FFB800 100%)',
                'icon_svg' => '<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z"/><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"/>',
                'description' => 'Engineering converts daydream sketches into kinetic reality. Young engineers understand structural loads, electrical resistance, servo articulation, and parametric 3D CAD modeling to conquer real hardware challenges.',
                'what_learn' => [
                    'Kinematic mechanisms (gears, pulleys, linkages, levers)',
                    'Ohm’s law, breadboarding & embedded circuits',
                    'Microcontroller firmware (Arduino, ESP32, Raspberry Pi Pico)',
                    'Parametric 3D CAD design & rapid additive manufacturing',
                    'Autonomous robotics (line followers, ultrasonic rovers)',
                    'Structural stress testing & aerospace aerodynamics',
                ],
                'outcomes' => [
                    '3D print custom mechanical parts designed from scratch in CAD',
                    'Wire and solder complete printed circuit prototypes',
                    'Program autonomous obstacle-avoiding mobile robotics',
                    'Calculate structural load safety factors for bridges & towers',
                    'Compete in FIRST LEGO League & VEX Robotics championships',
                ],
                'career_paths' => [
                    'Robotics Mechatronics Lead',
                    'Aerospace Hardware Designer',
                    'Renewable Energy Systems Engineer',
                    'Embedded Firmware Architect',
                    'Biomedical Prosthetics Engineer',
                ],
                'sort_order' => 3,
                'stages' => [
                    [
                        'stage_name' => 'Tinker Mechanics',
                        'age_band' => 'Ages 3–5',
                        'min_age' => 3,
                        'max_age' => 5,
                        'focus_title' => 'Balance, Levers & Kinetic Momentum',
                        'description' => 'Large gear linkages, pneumatic tubes, and modular magnetic circuits that introduce the sensation of mechanical torque, balance points, and electrical continuity.',
                        'skills' => ['Structural stability (wide base vs apex)', 'Gear rotation direction prediction', 'Simple electric circuit completion', 'Gravity marble run routing'],
                        'milestones' => ['Assembled 5-gear kinetic transmission', 'Illuminated LED with conductive copper tape', 'Built 60cm cantilever tower with wood planks'],
                        'tools_used' => ['LEGO DUPLO Tech Machines', 'LittleBits magnetic modules', 'Conductive play-dough', 'Wooden balance trusses'],
                        'featured_project' => 'Kinetic Marble Coaster with Manual Crank-Elevator & Loop-the-Loop',
                    ],
                    [
                        'stage_name' => 'Gear & Kinetic Crafters',
                        'age_band' => 'Ages 6–8',
                        'min_age' => 6,
                        'max_age' => 8,
                        'focus_title' => 'Mechanical Advantage & Motorized Rigs',
                        'description' => 'Constructing compound gearboxes, motorized winches, and rubber-band powered rovers while observing gear ratios and friction management.',
                        'skills' => ['Gear ratio calculations (speed vs torque)', 'Pulley mechanical advantage', 'Switch wiring & polarity reversal', 'Hydraulic syringe actuation'],
                        'milestones' => ['Built functional hydraulic scissor lift', 'Engineered car that traveled 8 meters on inertia', 'Wired dual-direction DC motor buggy'],
                        'tools_used' => ['LEGO Spike Essential / WeDo', 'Cardboard laser-cut chassis', 'DC hobby motors & battery packs', 'Pneumatic plastic syringes'],
                        'featured_project' => 'Hydraulic Cardboard Excavator with 3-Axis Arm Movement & Claw',
                    ],
                    [
                        'stage_name' => 'Arduino & Sensor Operators',
                        'age_band' => 'Ages 9–11',
                        'min_age' => 9,
                        'max_age' => 11,
                        'focus_title' => 'Breadboarding, C++ Firmware & Ultrasonic Echo',
                        'description' => 'Breadboard circuits with resistors, LEDs, and servos. Flash C++ firmware onto Arduino boards to read ultrasonic distance and light sensors in real time.',
                        'skills' => ['Breadboard bus wiring', 'Ohm’s law resistor calculation', 'Pulse-Width Modulation (PWM) speed control', 'Ultrasonic sensor triggering'],
                        'milestones' => ['Wired complete automated smart nightlight', 'Calibrated ultrasonic radar sweep on servo', 'Soldered first prototype PCB wire header'],
                        'tools_used' => ['Arduino Uno / Nano', 'Solderless breadboards', 'Ultrasonic HC-SR04 sensor', 'Tinkercad Circuits simulator'],
                        'featured_project' => 'Ultrasonic Smart Radar with Servo Sweep & Audio Threat Proximity Buzzer',
                    ],
                    [
                        'stage_name' => 'Autonomous Rover Builders',
                        'age_band' => 'Ages 12–14',
                        'min_age' => 12,
                        'max_age' => 14,
                        'focus_title' => '3D CAD Modeling & Multi-Sensor Rovers',
                        'description' => 'Design custom wheel hubs and sensor brackets in Autodesk Fusion 360, 3D print them, and assemble two-wheel differential drive autonomous rovers.',
                        'skills' => ['Parametric 3D CAD sketch constraints', '3D slicing (layer height, infill)', 'H-Bridge motor driver circuitry', 'PID line-tracking algorithms'],
                        'milestones' => ['Designed & 3D printed custom rover chassis', 'Programmed autonomous line-following bot', 'Calibrated infrared reflectometer sensors'],
                        'tools_used' => ['Autodesk Fusion 360 / Onshape', 'Bambu / Ender 3D Printers', 'L298N Motor Driver module', 'IR reflectance sensor arrays'],
                        'featured_project' => 'Autonomous Maze-Solving Rover with Custom 3D Printed Chassis & Dual IR Sensors',
                    ],
                    [
                        'stage_name' => 'Aerospace & IoT Hardware Innovators',
                        'age_band' => 'Ages 15–18',
                        'min_age' => 15,
                        'max_age' => 18,
                        'focus_title' => 'ESP32 Telemetry, Drones & Custom PCBs',
                        'description' => 'Design custom schematics and route real 2-layer PCBs in KiCad. Connect hardware to cloud MQTT brokers and engineer flight telemetry payloads.',
                        'skills' => ['KiCad schematic & PCB trace routing', 'Surface-mount device (SMD) soldering', 'ESP32 Wi-Fi / Bluetooth telemetry', 'Quadcopter flight controller tuning'],
                        'milestones' => ['Fabricated custom manufactured printed circuit board', 'Streamed temperature & GPS data to cloud MQTT', 'Built working quadcopter drone from carbon fiber components'],
                        'tools_used' => ['KiCad PCB Suite', 'ESP32 NodeMCU', 'Digital oscilloscope & bench PSU', 'MQTT Broker & Grafana dashboard'],
                        'featured_project' => 'Solar-Powered Environmental Weather Station with Custom PCB & Cloud Grafana Telemetry',
                    ],
                ],
            ],
            [
                'name' => 'Arts',
                'slug' => 'arts',
                'discipline' => 'arts',
                'tagline' => 'Weaponize Imagination. Sculpt 3D Worlds & Visual Chaos.',
                'ages' => '3–18',
                'color' => '#FF007F',
                'accent_color' => '#2D0017',
                'gradient' => 'linear-gradient(135deg,#2D0017 0%,#700038 50%,#FF007F 100%)',
                'icon_svg' => '<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 21a4 4 0 01-4-4V5a2 2 0 012-2h4a2 2 0 012 2v12a4 4 0 01-4 4zm0 0h12a2 2 0 002-2v-4a2 2 0 00-2-2h-2.343M11 7.343l1.657-1.657a2 2 0 012.828 0l2.829 2.829a2 2 0 010 2.828l-8.486 8.485M7 17h.01"/>',
                'description' => 'The "A" in STEAM is not decorative—it is the catalyst that turns raw technological horsepower into human connection. Students explore generative visual synthesis, spatial UI design, procedural 3D sculpture, and narrative worldbuilding.',
                'what_learn' => [
                    'Vector illustration, grid systems & typography hierarchy',
                    'Stop-motion & digital frame-by-frame 2D animation',
                    '3D digital sculpting & procedural texture mapping',
                    'User Experience (UX) wireframing & interactive prototyping',
                    'Generative art programming (Processing / p5.js)',
                    'Audio synthesis, sound design & spatial sonic scoring',
                ],
                'outcomes' => [
                    'Assemble an industry-standard digital creative portfolio',
                    'Sculpt and rig animated 3D assets ready for game engines',
                    'Prototype clickable app interfaces validated with real users',
                    'Exhibit kinetic media installations at TLab annual showcase',
                    'Publish digital storybooks and animated shorts',
                ],
                'career_paths' => [
                    'XR Creative Director',
                    'Technical 3D Artist',
                    'Product Experience Designer (UI/UX)',
                    'Generative Media Specialist',
                    'Animation & Motion Director',
                ],
                'sort_order' => 4,
                'stages' => [
                    [
                        'stage_name' => 'Color Magicians',
                        'age_band' => 'Ages 3–5',
                        'min_age' => 3,
                        'max_age' => 5,
                        'focus_title' => 'Chromatic Expression & Form Discovery',
                        'description' => 'Tactile clay sculpting, shadow puppetry, fingerprint character design, and learning how colors express temperature, mood, and narrative.',
                        'skills' => ['Primary & secondary color mixing', 'Fine motor clay manipulation', 'Shadow scale & perspective', 'Expressive character sketching'],
                        'milestones' => ['Sculpted full cast of clay creatures', 'Created 1-minute audio-recorded shadow puppet play', 'Mixed 24-color hue wheel from 3 primaries'],
                        'tools_used' => ['Polymer non-hardening clay', 'Overhead light projectors', 'Finger gouache paints', 'Tactile texture stamps'],
                        'featured_project' => 'Glow-in-the-Dark Shadow Puppet Theater with Custom Clay Beasties',
                    ],
                    [
                        'stage_name' => 'Lego StoryCrafters & Pixel Artists',
                        'age_band' => 'Ages 6–8',
                        'min_age' => 6,
                        'max_age' => 8,
                        'focus_title' => 'Stop-Motion Animation & Isometric Pixels',
                        'description' => 'Children capture frame-by-frame stop motion with clay and LEGO, write three-act micro-scripts, and design 16x16 retro pixel-art characters.',
                        'skills' => ['Stop-motion frame rates (12fps onion skinning)', 'Storyboarding beat-sheets', 'Pixel grid proportion', 'Sound effect foley recording'],
                        'milestones' => ['Directed 60-second stop-motion animation', 'Created 8-character pixel hero roster', 'Voiced & edited custom audio track'],
                        'tools_used' => ['Stop Motion Studio app', 'Tablet ring lights', 'Piskel / Aseprite', 'Foley sound box props'],
                        'featured_project' => '60-Second Stop-Motion Sci-Fi Film: "The Martian Brick Escape"',
                    ],
                    [
                        'stage_name' => '3D World Sculptors',
                        'age_band' => 'Ages 9–11',
                        'min_age' => 9,
                        'max_age' => 11,
                        'focus_title' => 'Digital Sculpting, Lighting & Vector Design',
                        'description' => 'Transitioning from flat 2D to volumetric 3D. Sculpting organic monsters in Nomad Sculpt and drafting clean vector logos in Figma.',
                        'skills' => ['Digital clay voxel manipulation', 'Vector pen tool bezier curve mastery', '3-point studio lighting setup', 'Color palette contrast theory'],
                        'milestones' => ['Sculpted high-detail 3D fantasy creature', 'Designed complete brand identity badge kit', 'Rendered dramatic 4K digital art piece'],
                        'tools_used' => ['Nomad Sculpt / Blender basics', 'Figma vector canvas', 'Apple Pencil / Drawing tablets', 'MagicaVoxel'],
                        'featured_project' => 'High-Detail Voxel Cyber-City Diorama Rendered in 3D Isometric View',
                    ],
                    [
                        'stage_name' => 'UX Cyber-Designers',
                        'age_band' => 'Ages 12–14',
                        'min_age' => 12,
                        'max_age' => 14,
                        'focus_title' => 'Interactive UI/UX & Generative p5.js Code Art',
                        'description' => 'Writing JavaScript (p5.js) that paints algorithmic geometry on mouse movement, and designing mobile app user flows in professional design suites.',
                        'skills' => ['Information architecture & user flows', 'Interactive Figma smart animate prototypes', 'Generative math art (sine waves, particle vectors)', 'Design accessibility (WCAG contrast)'],
                        'milestones' => ['Engineered clickable 12-screen mobile app mockup', 'Created algorithmic audio-reactive visualizer in code', 'Conducted usability tests on 5 peer testers'],
                        'tools_used' => ['Figma Advanced', 'p5.js Web Editor', 'Audacity sound editor', 'Spline 3D web interactive'],
                        'featured_project' => 'Interactive Mental Health Mobile App Prototype with Custom Algorithmic Ambient Soundscape',
                    ],
                    [
                        'stage_name' => 'Immersive XR Creators',
                        'age_band' => 'Ages 15–18',
                        'min_age' => 15,
                        'max_age' => 18,
                        'focus_title' => 'Blender 3D Rigging, Spatial XR & Game Engines',
                        'description' => 'Pre-college portfolio specialization. Sculpting, retopology, bone rigging in Blender, and importing assets into Unreal Engine / Unity for interactive environments.',
                        'skills' => ['Skeletal bone rigging & inverse kinematics', 'PBR shader node networks', 'Spatial audio environment design', 'Interactive game engine lighting & post-processing'],
                        'milestones' => ['Rigged fully walk-cycled 3D avatar', 'Created playable VR/WebGL virtual art gallery', 'Curated comprehensive Behance / ArtStation portfolio'],
                        'tools_used' => ['Blender 4.x', 'Unity / Unreal Engine 5', 'Substance Painter basics', 'DaVinci Resolve'],
                        'featured_project' => 'Playable WebGL Cyberpunk African Megacity Interactive Art Installation',
                    ],
                ],
            ],
            [
                'name' => 'Mathematics',
                'slug' => 'mathematics',
                'discipline' => 'mathematics',
                'tagline' => 'Decode Universe Source Code. Out-Think Supercomputers.',
                'ages' => '3–18',
                'color' => '#9D00FF',
                'accent_color' => '#1C0033',
                'gradient' => 'linear-gradient(135deg,#1C0033 0%,#4C0082 50%,#9D00FF 100%)',
                'icon_svg' => '<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 7h6m0 10v-3m-3 3h.01M9 17h.01M9 14h.01M12 14h.01M15 11h.01M12 11h.01M9 11h.01M7 21h10a2 2 0 002-2V5a2 2 0 00-2-2H7a2 2 0 00-2 2v14a2 2 0 002 2z"/>',
                'description' => 'No mind-numbing repetitive worksheets. Math at TLab is tactical strategy, pattern decipherment, game theory tournaments, cryptographic ciphers, and hyper-speed mental visualization.',
                'what_learn' => [
                    'Mental abacus arithmetic & Vedic calculation algorithms',
                    'Spatial geometry, tessellations & topological puzzles',
                    'Combinatorics, probability & predictive analytics',
                    'Number theory, modular arithmetic & RSA encryption ciphers',
                    'Game theory (Nash equilibrium, minimax tournament strategy)',
                    'Statistical data inference & stochastic modeling',
                ],
                'outcomes' => [
                    'Calculate complex multi-digit operations mentally in seconds',
                    'Solve international Olympiad-style lateral thinking problems',
                    'Crack and compose cryptographic substitution & cipher algorithms',
                    'Model unpredictable real-world events using probability simulations',
                    'Achieve verified rankings on global speed calculation leaderboards',
                ],
                'career_paths' => [
                    'Quantitative Financial Analyst',
                    'Cryptographer & Security Theorist',
                    'Data Science Algorithmist',
                    'Game Theory Strategist',
                    'Actuarial Risk Architect',
                ],
                'sort_order' => 5,
                'stages' => [
                    [
                        'stage_name' => 'Pattern Whisperers',
                        'age_band' => 'Ages 3–5',
                        'min_age' => 3,
                        'max_age' => 5,
                        'focus_title' => 'Subitizing, Geometric Sorting & Symmetry',
                        'description' => 'Developing the core number sense: instantly recognizing dot quantities without counting, sorting geometric solids, and physical balance equations.',
                        'skills' => ['Subitizing numbers 1–10', '2D to 3D shape identification', 'Equal weight balance scale logic', 'Sequencing alternating color patterns'],
                        'milestones' => ['Recognized dice quantities instantly in under 1 second', 'Built self-supporting arched block doorway', 'Solved 12-piece geometric tangram puzzle'],
                        'tools_used' => ['Numicon tactile shapes', 'Two-pan balance scale', 'Tangram wooden puzzles', 'Large visual abacus'],
                        'featured_project' => 'Giant Geometric Tangram Animal Wall Mural & Balance Scale Discovery Lab',
                    ],
                    [
                        'stage_name' => 'Abacus Speedsters & Logic Knights',
                        'age_band' => 'Ages 6–8',
                        'min_age' => 6,
                        'max_age' => 8,
                        'focus_title' => 'Mental Abacus & Chess Board Tactics',
                        'description' => 'Soroban abacus bead manipulation translates into mental visualization beads. Children solve addition and subtraction faster than adults with calculators.',
                        'skills' => ['Soroban abacus bead technique', 'Mental visualization addition/subtraction', 'Chess piece value & basic checkmate motifs', 'Magic square matrix calculation'],
                        'milestones' => ['Calculated 5 consecutive 2-digit additions mentally in 6 seconds', 'Checkmated automated chess engine at Level 3', 'Solved 3x3 magic square from scratch'],
                        'tools_used' => ['Japanese 13-rod Soroban abacus', 'Tournament chess clock & sets', 'KenKen grid puzzles', 'Rapid flash card projectors'],
                        'featured_project' => 'Speed Calculation Blitz Showdown & 3x3 Magic Square Cipher Decryption',
                    ],
                    [
                        'stage_name' => 'Olympiad Puzzlers',
                        'age_band' => 'Ages 9–11',
                        'min_age' => 9,
                        'max_age' => 11,
                        'focus_title' => 'Prime Sieve, Fibonacci & Modular Clocks',
                        'description' => 'Diving into number theory mysteries: primes, modular arithmetic (clock math), the golden ratio in nature, and competitive Olympiad word problems.',
                        'skills' => ['Sieve of Eratosthenes prime generation', 'Fibonacci sequence spirals in nature', 'Modular clock arithmetic', 'Pigeonhole principle deduction'],
                        'milestones' => ['Factored 4-digit composite numbers into prime factors', 'Calculated day-of-week for any historical calendar date mentally', 'Scored in top bracket of mock Olympiad round'],
                        'tools_used' => ['Olympiad competition problem sets', 'Doomsday calendar algorithm charts', 'Compass & straightedge precision tools', 'Geogebra geometry suite'],
                        'featured_project' => 'Sacred Fibonacci Geometry Drawing Machine & Caesar Cipher Wheel',
                    ],
                    [
                        'stage_name' => 'Cryptographers & Game Theorists',
                        'age_band' => 'Ages 12–14',
                        'min_age' => 12,
                        'max_age' => 14,
                        'focus_title' => 'Ciphers, Frequency Analysis & Probability',
                        'description' => 'Cracking encrypted messages using letter frequency analysis, computing poker and dice probability trees, and exploring prisoner’s dilemma game matrices.',
                        'skills' => ['Frequency analysis decryption', 'Permutations & combinations (nCr, nPr)', 'Bayesian conditional probability trees', 'Minimax strategic decision trees'],
                        'milestones' => ['Decrypted intercepted Vigenère polyalphabetic cipher', 'Calculated exact compound odds for multi-dice tournaments', 'Programmed optimal tit-for-tat game theory bot'],
                        'tools_used' => ['Python math library', 'Desmos Graphing Calculator', 'Vigenère Cipher wheels', 'Monte Carlo probability simulators'],
                        'featured_project' => 'Enigma Machine Simulation & Monte Carlo Casino Probability Engine',
                    ],
                    [
                        'stage_name' => 'Quantum Data Scientists',
                        'age_band' => 'Ages 15–18',
                        'min_age' => 15,
                        'max_age' => 18,
                        'focus_title' => 'Linear Algebra, Calculus & Algorithmic Modeling',
                        'description' => 'Pre-university mathematical firepower. Matrix transformations, gradient descent intuition, RSA public-key math, and modeling chaotic real-world systems.',
                        'skills' => ['Matrix multiplication & vector transformations', 'Derivative rate of change intuition', 'RSA modular exponentiation public-key math', 'Markov chains & stochastic states'],
                        'milestones' => ['Implemented RSA key-pair generation from scratch in Python', 'Modeled pandemic contagion spread using differential equations', 'Trained linear regression gradient descent from mathematical first principles'],
                        'tools_used' => ['NumPy & Matplotlib', 'Wolfram Alpha / Mathematica', 'LaTeX scientific document compiler', 'Jupyter Lab'],
                        'featured_project' => 'Custom 2048-bit RSA Encryption Engine with Mathematical Proof & Key-Exchange Demo',
                    ],
                ],
            ],
        ];

        foreach ($programs as $progData) {
            $stages = $progData['stages'];
            unset($progData['stages']);

            $program = Program::updateOrCreate(
                ['slug' => $progData['slug']],
                $progData
            );

            foreach ($stages as $i => $stageData) {
                $stageData['sort_order'] = $i + 1;
                $stageData['program_id'] = $program->id;

                ProgramGrowthStage::updateOrCreate(
                    [
                        'program_id' => $program->id,
                        'stage_name' => $stageData['stage_name'],
                    ],
                    $stageData
                );
            }
        }
    }
}
